### ISSUE TITLE
Getting an error while running with claude

### ISSUE THREAD

**Issue by pentestguy** [yevh/TaaC-AI#6]
Hey,

I am trying to run below command but getting an error.

python3 TaaC-AI.py --model claude --cross-validation claude AuthService-example.yaml 

![Screenshot 2024-05-23 at 5 47 28 PM](https://github.com/yevh/TaaC-AI/assets/8958944/54c55561-dbd4-49fd-a028-3bac09c093dc)

**Comment by yevh** [comment]
Hey @pentestguy, `--cross-validation` intended for threats validation by another LLM (not the same one, for example gpt-4, or mistral). If you want to generate a list of threats with claude, you may just run `python3 TaaC-AI.py --model claude AuthService-example.yaml`.

**Comment by pentestguy** [comment]
Hi @yevh,

The previous command I tried from the documentation itself. And when I am trying another LLM then I am facing the below error.

` python3 TaaC-AI.py --model mistral --cross-validation claude AuthService-example.yaml`

![Screenshot 2024-05-23 at 10 29 48 PM](https://github.com/yevh/TaaC-AI/assets/8958944/0666de53-8131-44c1-80c6-941b8d27b754)

**Comment by yevh** [comment]
Hey @pentestguy, I can't reproduce this.

<img width="987" alt="Screenshot 2024-05-24 at 10 56 16" src="https://github.com/yevh/TaaC-AI/assets/14802765/7556f0b8-599f-4d96-b020-b837185898b5">

However, I want to help you resolve this. Do you import the [OpenAI API](https://openai.com/blog/openai-api) [Anthropic API](https://docs.anthropic.com/claude/reference/getting-started-with-the-api) as environment variables? In the case of Mistral, you should install it and run it in a separate terminal window as described in the README.

Also, could you check which Python version and dependencies versions you used? In my case, it looks as follows:

```
(venv) ym@% python --version
Python 3.12.3
(venv) ym@% pip list
Package            Version
------------------ --------
annotated-types    0.7.0
anthropic          0.26.1
anyio              4.3.0
certifi            2024.2.2
charset-normalizer 3.3.2
distro             1.9.0
filelock           3.14.0
fsspec             2024.5.0
h11                0.14.0
httpcore           1.0.5
httpx              0.27.0
huggingface-hub    0.23.1
idna               3.7
Jinja2             3.1.4
jiter              0.4.0
MarkupSafe         2.1.5
ollama             0.2.0
openai             1.30.2
packaging          24.0
pip                24.0
pydantic           2.7.1
pydantic_core      2.18.2
PyYAML             6.0.1
requests           2.32.2
sniffio            1.3.1
tokenizers         0.19.1
tqdm               4.66.4
typing_extensions  4.12.0
urllib3            2.2.1
```

**Comment by pentestguy** [comment]
Hi @yevh 

Thanks for quick reply.

I checked the python version and dependencies and it looks good.
![Screenshot 2024-05-24 at 4 55 59 PM](https://github.com/yevh/TaaC-AI/assets/8958944/66b904b7-9f40-40b1-9413-bfa78b9484e3)

Well I am trying mistral only and running in on the another terminal, also imported  both api keys and  please find the below screenshot for your reference.
![Screenshot 2024-05-24 at 5 10 21 PM](https://github.com/yevh/TaaC-AI/assets/8958944/a0a851e5-56e4-4c8a-9925-a22bad0ec008)

**Please note that I am using my personal OpenAI account** so currently there is no active plan. Does due to that am I am getting this error?

**Comment by yevh** [comment]
Hey @pentestguy, it should not. Could you update the python, run the following commands and provide the output:

```
python TaaC-AI.py AuthService-example.yaml --debug

python TaaC-AI.py --model mistral OrderService-example.yaml --debug

python TaaC-AI.py --model gpt-4 OrderService-example.yaml --debug

python TaaC-AI.py --model claude AuthService-example.yaml --debug
```

**Comment by pentestguy** [comment]
Hi @yevh,

As I mentioned I am trying it own my personal account which is free one. And for GPT and Claude it shows rate limit or less credit. But it still shows the "Done! The report has been successfully generated" message. 

If anyone using it without debug then it might confused them, that's what happens in my case because in the generated report there is no information about the threats.
![Screenshot 2024-05-24 at 5 55 16 PM](https://github.com/yevh/TaaC-AI/assets/8958944/291233d6-a466-4abb-aa09-79d0cf7fb6dc)

I will give a shot with paid version of GPT and Claude. As it's working fine with Mistral

Your quick help is really appreciated :) I have a quick suggestion for you about DFD(Data Flow Diagram) like I saw in the pytm tool, that will help a lot anyone to understand the flow in detail.

Thank you so much!
