### ISSUE TITLE
Why does Mistral AI also needed OpenIAI API Key?

### ISSUE THREAD

**Issue by pentestguy** [yevh/TaaC-AI#7]
Hey @yevh 

I hope you are doing well.

I am curious why the OpenAI API key is needed when using the Mistral model.

Is Mistral going with the GPT action? 

I also tried to containerize the solution and it's working fine for me :) 

Waiting for your reply, thank you!

**Comment by yevh** [comment]
Hey @pentestguy  an OpenAI API key is not needed when using the Mistral model. It will be fixed in the future. Thank you for reporting! Feel free to contribute.

**Comment by pentestguy** [comment]
Hi @yevh ,

Thank you so much for your response.
